CREATE DATABASE Test
GO

USE Test
GO

CREATE TABLE TestTable
	(
		Id int PRIMARY KEY IDENTITY NOT NULL,
		RandomDate DATE NOT NULL,
		RandomText nvarchar(100) NOT NULL
	)

DECLARE @RowCount INT
DECLARE @RowString VARCHAR(10)
DECLARE @Random INT
DECLARE @Upper INT
DECLARE @Lower INT
DECLARE @InsertDate DATETIME

SET @Lower = -3650;
SET @Upper = -1;
SET @RowCount = 0;


WHILE @RowCount < 10000000
BEGIN

	SET @RowString = CAST(@RowCount AS VARCHAR(10))

	SELECT @Random = ROUND(((@Upper - @Lower -1) * RAND() + @Lower), 0)

	SET @InsertDate = DATEADD(dd, @Random, GETDATE());

	INSERT INTO TestTable
		(RandomDate, RandomText)
	VALUES
		(DATEADD(dd, 1, @InsertDate), 'random text that''s not random')

	SET @RowCount = @RowCount + 1
END

-- INSERTION COSTS (WITH DEFAULT TABLE GROWTH AND INITIAL SIZE)
-- AROUND 10 MINUTES!


-- ACTUAL PERFORMANCE TEST WITH SEARCH BETWEEN DATES

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2009'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH CACHE, TOOK 00:00:08

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2012'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH CACHE, TOOK 00:00:04




-- THE FOLLOWING QUERIES WITH NO CACHE -- 

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2009'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH NO CACHE, TOOK 00:00:09

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2012'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH NO CACHE, TOOK 00:00:04


DBCC DROPCLEANBUFFERS
DBCC FREEPROCCACHE
GO