USE Test
GO

CREATE NONCLUSTERED INDEX [IX_TEST_DATE]
	ON TestTable
(
	RandomDate
)
GO


-- ACTUAL PERFORMANCE TEST WITH SEARCH BETWEEN DATES

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2009'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH CACHE, TOOK 00:00:08

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2012'
AND '01.01.2015'

-- THE QUERY ABOVE, WITHOUT INDEXING, WITH CACHE, TOOK 00:00:04




-- THE FOLLOWING QUERIES WITH NO CACHE -- 

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2009'
AND '01.01.2015'

-- THE QUERY ABOVE, WITH INDEXING, WITH NO CACHE, TOOK 00:00:09

SELECT RandomDate FROM TestTable
WHERE RandomDate BETWEEN '03.11.2012'
AND '01.01.2015'

-- THE QUERY ABOVE, WITH INDEXING, WITH NO CACHE, TOOK 00:00:04


DBCC DROPCLEANBUFFERS
DBCC FREEPROCCACHE
GO

-- I GUESS I AM DOING SOMETHING WRONG, AS THERE WAS ABSOLUTELY NO CHANGE IN THE SPEED FOR THE QUERIES ABOVE. NO IDEA WHAT'S GOING ON.